import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/navbar";
import { createClient } from "@/utils/supabase/server";
import { redirect } from "next/navigation";

const geistSans = Geist({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-geist-sans",
    adjustFontFallback: false, // Prevents auto font fallback adjustment
});

const geistMono = Geist_Mono({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-geist-mono",
    adjustFontFallback: false,
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const supabase = await createClient();
    const { data, error } = await supabase.auth.getUser()
    if (error) {
        redirect('/')
    }
    return (
        <>
            {children}
        </>
    );
}
